// Generates supabase/seed.sql from the canonical CSV seed (lib/seedCsv.ts),
// reusing the exact same parser the app uses so the seed can never drift from
// the app's data model. Run with: npm run db:seed:gen
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parseTeamCsv } from "../lib/parseTeamCsv";
import { SEED_CSV } from "../lib/seedCsv";
import type { Customer, Item } from "../lib/types";

const quote = (value: string): string => `'${value.replace(/'/g, "''")}'`;
// The app models empty text as "" (never null), so text columns keep "".
const text = (value: string): string => quote(value);
// Date-only fields are "" when unset in the app; those map to SQL NULL.
const dateOrNull = (value: string): string => (value ? quote(value) : "NULL");
const numOrNull = (value: number | null): string => (value === null ? "NULL" : String(value));
const jsonb = (value: unknown): string => `${quote(JSON.stringify(value))}::jsonb`;

function customerRow(c: Customer): string {
  return [
    quote(c.id),
    text(c.name),
    text(c.province),
    text(c.salesOwner),
    text(c.contactPerson),
    text(c.phone),
    text(c.email),
    text(c.lineId),
    text(c.color),
    jsonb(c.interactions),
    quote(c.createdAt),
  ].join(", ");
}

function itemRow(i: Item): string {
  return [
    quote(i.id),
    i.customerId ? quote(i.customerId) : "NULL",
    text(i.qtNo),
    text(i.invNo),
    quote(i.channel),
    text(i.itemType),
    text(i.detail),
    numOrNull(i.price),
    quote(i.execStatus),
    quote(i.resultStatus),
    quote(i.reportStatus),
    quote(i.renewalStatus),
    text(i.target),
    text(i.actual),
    text(i.metricName),
    text(i.metricUnit),
    numOrNull(i.targetValue),
    numOrNull(i.actualValue),
    dateOrNull(i.reportSentDate),
    text(i.link),
    String(i.rating),
    dateOrNull(i.deadline),
    dateOrNull(i.publishDate),
    dateOrNull(i.finishedDate),
    text(i.notes),
    dateOrNull(i.followUpDate),
    text(i.followUpNote),
    quote(i.priority),
    String(i.progress),
    jsonb(i.checklist),
    jsonb(i.activity),
    quote(i.createdAt),
    quote(i.updatedAt),
  ].join(", ");
}

const CUSTOMER_COLS =
  "id, name, province, sales_owner, contact_person, phone, email, line_id, color, interactions, created_at";
const ITEM_COLS =
  "id, customer_id, qt_no, inv_no, channel, item_type, detail, price, exec_status, result_status, " +
  "report_status, renewal_status, target, actual, metric_name, metric_unit, target_value, actual_value, " +
  "report_sent_date, link, rating, deadline, publish_date, finished_date, notes, follow_up_date, " +
  "follow_up_note, priority, progress, checklist, activity, created_at, updated_at";

const { customers, items, members } = parseTeamCsv(SEED_CSV);

const out: string[] = [
  "-- Generated by scripts/generate-seed.ts from lib/seedCsv.ts — do not edit by hand.",
  "-- Regenerate with: npm run db:seed:gen",
  "",
];

if (members.length > 0) {
  out.push("insert into public.members (name) values");
  out.push(members.map((m) => `  (${quote(m)})`).join(",\n") + "\non conflict (name) do nothing;");
  out.push("");
}

out.push(`insert into public.customers (${CUSTOMER_COLS}) values`);
out.push(customers.map((c) => `  (${customerRow(c)})`).join(",\n") + "\non conflict (id) do nothing;");
out.push("");

out.push(`insert into public.items (${ITEM_COLS}) values`);
out.push(items.map((i) => `  (${itemRow(i)})`).join(",\n") + "\non conflict (id) do nothing;");
out.push("");

const outPath = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../supabase/seed.sql");
writeFileSync(outPath, out.join("\n"), "utf8");
console.log(
  `Wrote ${outPath}\n  ${customers.length} customers, ${items.length} items, ${members.length} members.`,
);
